### ISSUE TITLE
Problems related to displaying/formatting incorrectly formatted coins

### ISSUE THREAD

**Issue by Ferks-FK** [Ctrlpanel-gg/panel#1248]
### What is your request about?

After [PR](https://github.com/Ctrlpanel-gg/panel/pull/1211) was merged in the last update, that which by the way was a big change, in some places the display of coins has not been updated, and they are displayed incorrectly.
This bug report aims to gather all the places where these errors exist, so that they can be corrected in the next version.

Current known:

- [x] When installing the panel, when creating the first user of the system, the initial credits are entered incorrectly in the DB.
- [x] On the administrator overview page, in the count of users' total coins.
- [x] Voucher modal success notification. [Screenshot here](https://github.com/Ctrlpanel-gg/panel/issues/1248#issuecomment-3033610007)
- [x] Admin user overview page. [Screenshot here](https://github.com/Ctrlpanel-gg/panel/issues/1248#issuecomment-3045968858)

### Branch

main

### CtrlPanel Logs

```Shell

```

**Comment by BOXmineYT** [comment]
![Image](https://github.com/user-attachments/assets/27835569-5511-4f43-b86d-cc8ca4780de0)
![Image](https://github.com/user-attachments/assets/33cb483b-0653-4e70-bef3-56869451bc76)

**Comment by BOXmineYT** [comment]
@Ferks-FK 

![Image](https://github.com/user-attachments/assets/6ccde42a-3e37-49b1-b83f-d0001298898f)

**Comment by MrWeez** [comment]
> [@Ferks-FK](https://github.com/Ferks-FK)
> 
> ![Image](https://github.com/user-attachments/assets/6ccde42a-3e37-49b1-b83f-d0001298898f)

This is user overview page?

**Comment by 1day2die** [comment]
> > [@Ferks-FK](https://github.com/Ferks-FK)
> > ![Image](https://github.com/user-attachments/assets/6ccde42a-3e37-49b1-b83f-d0001298898f)
> 
> This is user overview page?

this is user detail i think

**Comment by LunarLoom24** [comment]
<img width="414" height="522" alt="Image" src="https://github.com/user-attachments/assets/2d7232fd-c641-4ebb-902a-229d04494cc6" />

**Comment by LunarLoom24** [comment]
<img width="299" height="53" alt="Image" src="https://github.com/user-attachments/assets/7bc69dcc-5931-48a6-9179-831b8012329f" />

**Comment by LunarLoom24** [comment]
<img width="177" height="48" alt="Image" src="https://github.com/user-attachments/assets/cde01a23-8984-471e-aa6c-ddfb83efcbba" />

<img width="94" height="41" alt="Image" src="https://github.com/user-attachments/assets/3993c83d-23af-4577-9aa2-47e70583f61c" /> real value shold be 60,000 -> 60k

**Comment by 1day2die** [comment]
@Ferks-FK  can be merged?

**Comment by MrWeez** [comment]
> @Ferks-FK  can be merged?

I think we can leave it open for now. Maybe someone find new display bug

**Comment by simbabimba-dev** [comment]
<img width="999" height="570" alt="Image" src="https://github.com/user-attachments/assets/49b2fc7a-3988-451a-91bc-2ed68ccc7c4a" />
@Ferks-FK @MrWeez 
This part is still using the number_format

**Comment by Ferks-FK** [comment]
> <img alt="Image" width="999" height="570" src="https://private-user-images.githubusercontent.com/79574809/478823449-49b2fc7a-3988-451a-91bc-2ed68ccc7c4a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2MjY4NzYsIm5iZiI6MTc1NTYyNjU3NiwicGF0aCI6Ii83OTU3NDgwOS80Nzg4MjM0NDktNDliMmZjN2EtMzk4OC00NTFhLTkxYmMtMmVkNjhjY2M3YzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE5VDE4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYjhkZjZmYjNmZDQzMTJiODVjZTI2MmNlOWQxMmVhYTMwODMyMjA1Mzg3N2M0N2Q4ZWQwODkzZDJjNDlhYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bnRBUNPdse7XFaDDXDe7-3kR7P-G5MGGlqzs969GgHY"> [@Ferks-FK](https://github.com/Ferks-FK) [@MrWeez](https://github.com/MrWeez) This part is still using the number_format

Already fixed.

**Comment by simbabimba-dev** [comment]
> > <img alt="Image" width="999" height="570" src="https://private-user-images.githubusercontent.com/79574809/478823449-49b2fc7a-3988-451a-91bc-2ed68ccc7c4a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2MjY4NzYsIm5iZiI6MTc1NTYyNjU3NiwicGF0aCI6Ii83OTU3NDgwOS80Nzg4MjM0NDktNDliMmZjN2EtMzk4OC00NTFhLTkxYmMtMmVkNjhjY2M3YzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE5VDE4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYjhkZjZmYjNmZDQzMTJiODVjZTI2MmNlOWQxMmVhYTMwODMyMjA1Mzg3N2M0N2Q4ZWQwODkzZDJjNDlhYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bnRBUNPdse7XFaDDXDe7-3kR7P-G5MGGlqzs969GgHY"> [@Ferks-FK](https://github.com/Ferks-FK) [@MrWeez](https://github.com/MrWeez) This part is still using the number_format
> 
> Already fixed.

yeah i saw that its fixed in the latest dev branch

**Comment by LunarLoom24** [comment]
<img width="499" height="597" alt="Image" src="https://github.com/user-attachments/assets/f0d1102f-d0cc-467f-94dc-4547a918a4ee" />

<img width="170" height="42" alt="Image" src="https://github.com/user-attachments/assets/ff789760-1f75-40ed-92bd-e8157f93136c" />


for me it still shows in weird format coins display

Version i am using: CtrlPanel [v1.1.2 - development]

**Comment by Ferks-FK** [comment]
> <img alt="Image" width="499" height="597" src="https://private-user-images.githubusercontent.com/67901751/480432837-f0d1102f-d0cc-467f-94dc-4547a918a4ee.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU3NzY1NTcsIm5iZiI6MTc1NTc3NjI1NywicGF0aCI6Ii82NzkwMTc1MS80ODA0MzI4MzctZjBkMTEwMmYtZDBjYy00NjdmLTk0ZGMtNDU0N2E5MThhNGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODIxVDExMzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzM2Q2Y2I0OTE0MzRkMjNmZGZiMWU2ZjZlZGNiNzI1MTNjYzMzN2FjZmQ4ZWRjZjFmNDE4Yjk3NDkwZWU2NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vmq6dFn4vcZS4I8FAMFpqhrfKmdudbyK4k-nipxAaLA"> <img alt="Image" width="170" height="42" src="https://private-user-images.githubusercontent.com/67901751/480433185-ff789760-1f75-40ed-92bd-e8157f93136c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU3NzY1NTcsIm5iZiI6MTc1NTc3NjI1NywicGF0aCI6Ii82NzkwMTc1MS80ODA0MzMxODUtZmY3ODk3NjAtMWY3NS00MGVkLTkyYmQtZTgxNTdmOTMxMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODIxVDExMzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzg5N2RmOTZjNDllZTFlMDI4YTBhMTFiOWFmMzQyNzI1N2RiMWRiY2FhYzMxMzQwZjZiMzRlM2Y4MGVkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eXL_uaQr3scNAghaK8zsl3zvZXzxpU8Jx_JeBQuiwA4">
> for me it still shows in weird format coins display
> 
> Version i am using: CtrlPanel [v1.1.2 - development]

That's because your currencies are in the thousands.
And it was coded to show thousands and cents separators in the formatting (which didn't exist before), so you think it's wrong, but it's not.
I understand that there are places where the separators are different, and that wasn't taken into account.
But it can be added.

**Comment by SyntaxCodez** [comment]
Yeah showing same for me, if it doesn’t get fixed, it will force me to switch dashboards and I will not switch back

**Comment by simbabimba-dev** [comment]
> When installing the panel, when creating the first user of the system, the initial credits are entered incorrectly in the DB.

I have fixed this and i will be releasing the pr soon for this

**Comment by KroZen-Dev** [comment]
I’d like to add that the issue with incorrect credits also occurs through the API: when adding credits via the API, you specify one amount, but a different amount is actually credited. Additionally, there may be incorrect display when fetching data via the API, but this has not been fully verified yet

**Comment by MrWeez** [comment]
> I’d like to add that the issue with incorrect credits also occurs through the API: when adding credits via the API, you specify one amount, but a different amount is actually credited. Additionally, there may be incorrect display when fetching data via the API, but this has not been fully verified yet

Ferks has been working on a PR project that should fix and improve the API, but at the moment it seems to be unfinished

**Comment by simbabimba-dev** [comment]
> > I’d like to add that the issue with incorrect credits also occurs through the API: when adding credits via the API, you specify one amount, but a different amount is actually credited. Additionally, there may be incorrect display when fetching data via the API, but this has not been fully verified yet
> 
> Ferks has been working on a PR project that should fix and improve the API, but at the moment it seems to be unfinished

can you uhh send me the pr link so i can also see if i can help

**Comment by MrWeez** [comment]
> > > I’d like to add that the issue with incorrect credits also occurs through the API: when adding credits via the API, you specify one amount, but a different amount is actually credited. Additionally, there may be incorrect display when fetching data via the API, but this has not been fully verified yet
> > 
> > 
> > Ferks has been working on a PR project that should fix and improve the API, but at the moment it seems to be unfinished
> 
> can you uhh send me the pr link so i can also see if i can help

#1257 #1262 #1267 - API fixes and small improvements
#1108 - New API features

**Comment by KroZen-Dev** [comment]
The problem is that if you enter 50 credits in the field, then upon registration, that amount is credited, divided by 1,000, or 0.05 credits. This means that to get 50 credits, you need to enter 50 * 1,000 in the field, or 50,000 credits. I tried to fix it myself, but I couldn't find the problem. Most likely, it's in one of the migrations

<img width="430" height="194" alt="Image" src="https://github.com/user-attachments/assets/e278e9bd-9751-470c-90dc-4a4106720edd" />

**Comment by MrWeez** [comment]
Currently in the testing phase.

**Comment by Ferks-FK** [comment]
> The problem is that if you enter 50 credits in the field, then upon registration, that amount is credited, divided by 1,000, or 0.05 credits. This means that to get 50 credits, you need to enter 50 * 1,000 in the field, or 50,000 credits. I tried to fix it myself, but I couldn't find the problem. Most likely, it's in one of the migrations
> 
> <img alt="Image" width="430" height="194" src="https://private-user-images.githubusercontent.com/109613115/540385908-e278e9bd-9751-470c-90dc-4a4106720edd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA0NzUwMzYsIm5iZiI6MTc3MDQ3NDczNiwicGF0aCI6Ii8xMDk2MTMxMTUvNTQwMzg1OTA4LWUyNzhlOWJkLTk3NTEtNDcwYy05MGRjLTRhNDEwNjcyMGVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIwN1QxNDMyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmEwNTM4OWY2MzczOGEyM2Y2NGI5MmE0YTU3OTk3ZDgwNWJjNWQwZDA1MWE3NWM2NDY0MjMxMzMwMTE1MWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GdFdg_i1Eficyhr9DKd2k79QRdsw9SiZBQ9qcUk7e94">

Hello, I tested this now in the development branch and was unable to reproduce the problem.

The account had 50 credits, the reward will also be 50 credits, and upon registration, the account had 100 credits.

**Comment by MrWeez** [comment]
Should be fixed in 1.2
